Repository PACKIT-Project/PACKIT-Backend, pull requests merged in 2023-12, with the labels that each got.

#16 [Backend] 인증 기능 개선 및 웹 & 모바일 API 분리
  src/main/java/site/packit/packit/domain/auth/constant/CookieConstant.java
  src/main/java/site/packit/packit/domain/auth/controller/AuthController.java
  src/main/java/site/packit/packit/domain/auth/dto/AuthenticationTokens.java
  src/main/java/site/packit/packit/domain/auth/dto/mobile/request/MobileLoginRequest.java
  src/main/java/site/packit/packit/domain/auth/dto/mobile/request/MobileTokenReissueRequest.java
  src/main/java/site/packit/packit/domain/auth/dto/mobile/response/MobileLoginResponse.java
  src/main/java/site/packit/packit/domain/auth/dto/mobile/response/MobileTokenReissueResponse.java
  src/main/java/site/packit/packit/domain/auth/dto/response/LoginResponse.java
  src/main/java/site/packit/packit/domain/auth/dto/response/TokenReissueResponse.java
  src/main/java/site/packit/packit/domain/auth/dto/web/response/WebTokenReissueResponse.java
  src/main/java/site/packit/packit/domain/auth/exception/AuthExceptionHandler.java
  src/main/java/site/packit/packit/domain/auth/filter/TokenAuthenticationFilter.java
  src/main/java/site/packit/packit/domain/auth/handler/CustomOAuth2AuthenticationFailureHandler.java
  src/main/java/site/packit/packit/domain/auth/handler/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/site/packit/packit/domain/auth/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/site/packit/packit/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/site/packit/packit/domain/auth/service/GlobalAuthService.java
  src/main/java/site/packit/packit/domain/auth/service/MobileAuthService.java
  src/main/java/site/packit/packit/domain/auth/service/TokenService.java
  src/main/java/site/packit/packit/domain/auth/service/WebAuthService.java
  src/main/java/site/packit/packit/domain/image/constant/ImageConstant.java
  src/main/java/site/packit/packit/domain/member/controller/MemberController.java
  src/main/java/site/packit/packit/domain/member/entity/Member.java
  src/main/java/site/packit/packit/domain/member/service/MemberService.java
  src/main/java/site/packit/packit/global/multipart/MultipartConfig.java
  src/main/java/site/packit/packit/global/security/SecurityConfig.java
  src/main/java/site/packit/packit/global/util/LoginResponseUtil.java
Labels: refactor

#17 [Backend] 인증 전략 수정 및 프론트 요구사항 적용
  src/main/java/site/packit/packit/domain/auth/controller/AuthController.java
  src/main/java/site/packit/packit/domain/auth/dto/mobile/response/MobileLoginResponse.java
  src/main/java/site/packit/packit/domain/auth/filter/TokenAuthenticationFilter.java
  src/main/java/site/packit/packit/domain/auth/handler/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/site/packit/packit/domain/auth/service/MobileAuthService.java
  src/main/java/site/packit/packit/domain/member/controller/MemberController.java
  src/main/java/site/packit/packit/domain/member/dto/MemberDto.java
  src/main/java/site/packit/packit/domain/member/dto/request/CheckMemberNicknameDuplicatedRequest.java
  src/main/java/site/packit/packit/domain/member/dto/request/UpdateMemberProfileRequest.java
  src/main/java/site/packit/packit/domain/member/dto/response/CheckMemberNicknameDuplicatedResponse.java
  src/main/java/site/packit/packit/domain/member/dto/response/GetMemberProfileResponse.java
  src/main/java/site/packit/packit/domain/member/dto/response/RegisterResponse.java
  src/main/java/site/packit/packit/domain/member/entity/Member.java
  src/main/java/site/packit/packit/domain/member/repository/MemberRepository.java
  src/main/java/site/packit/packit/domain/member/service/MemberService.java
  src/main/java/site/packit/packit/global/security/SecurityConfig.java
  src/main/java/site/packit/packit/global/util/LoginResponseUtil.java
Labels: feat, refactor

#23 [Backend] 기본 엔티티 수정
  src/main/java/site/packit/packit/domain/category/controller/CategoryController.java
  src/main/java/site/packit/packit/domain/category/entity/Category.java
  src/main/java/site/packit/packit/domain/category/repository/CategoryRepository.java
  src/main/java/site/packit/packit/domain/category/service/CategoryService.java
  src/main/java/site/packit/packit/domain/checkList/controller/CheckListController.java
  src/main/java/site/packit/packit/domain/checkList/dto/CreateCheckListRequest.java
  src/main/java/site/packit/packit/domain/checkList/dto/UpdateCheckListRequest.java
  src/main/java/site/packit/packit/domain/checkList/dto/UpdateListTitleRequest.java
  src/main/java/site/packit/packit/domain/checkList/entity/CheckList.java
  src/main/java/site/packit/packit/domain/checkList/excepiton/CheckListErrorCode.java
  src/main/java/site/packit/packit/domain/checkList/repository/CheckListRepository.java
  src/main/java/site/packit/packit/domain/checkList/service/CheckListService.java
  src/main/java/site/packit/packit/domain/cluster/controller/ClusterController.java
  src/main/java/site/packit/packit/domain/cluster/entity/Cluster.java
  src/main/java/site/packit/packit/domain/cluster/repository/ClusterRepository.java
  src/main/java/site/packit/packit/domain/cluster/service/ClusterService.java
  src/main/java/site/packit/packit/domain/item/controller/ItemController.java
  src/main/java/site/packit/packit/domain/item/dto/CreateItemReq.java
  src/main/java/site/packit/packit/domain/item/dto/UpdateItemReq.java
  src/main/java/site/packit/packit/domain/item/dto/UpdateItemTitleReq.java
  src/main/java/site/packit/packit/domain/item/entity/Item.java
  src/main/java/site/packit/packit/domain/item/repository/ItemRepository.java
  src/main/java/site/packit/packit/domain/item/service/ItemService.java
  src/main/java/site/packit/packit/domain/storage/controller/StorageController.java
  src/main/java/site/packit/packit/domain/storage/dto/StorageListDto.java
  src/main/java/site/packit/packit/domain/storage/dto/UpdateStorage.java
  src/main/java/site/packit/packit/domain/storage/repository/StorageRepository.java
  src/main/java/site/packit/packit/domain/storage/service/StorageService.java
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/dto/BringTravelRequest.java
  src/main/java/site/packit/packit/domain/travel/dto/CheckListDto.java
  src/main/java/site/packit/packit/domain/travel/dto/CreateTravelReq.java
  src/main/java/site/packit/packit/domain/travel/dto/GetTravelRequest.java
  src/main/java/site/packit/packit/domain/travel/dto/ItemDto.java
  src/main/java/site/packit/packit/domain/travel/dto/TravelDetailDto.java
  src/main/java/site/packit/packit/domain/travel/dto/TravelListDto.java
  src/main/java/site/packit/packit/domain/travel/dto/UpdateTravelRequest.java
  src/main/java/site/packit/packit/domain/travel/entity/Travel.java
  src/main/java/site/packit/packit/domain/travel/entity/TravelMember.java
  src/main/java/site/packit/packit/domain/travel/repository/TravelRepository.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: refactor

#25 [Backend] 동행자 관련 기능
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/dto/TravelInviteRes.java
  src/main/java/site/packit/packit/domain/travel/entity/Travel.java
  src/main/java/site/packit/packit/domain/travel/entity/TravelMember.java
  src/main/java/site/packit/packit/domain/travel/exception/TravelErrorCode.java
  src/main/java/site/packit/packit/domain/travel/repository/TravelMemberRepository.java
  src/main/java/site/packit/packit/domain/travel/repository/TravelRepository.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
  src/main/java/site/packit/packit/global/exception/MaxParticipantsExceededException.java
Labels: feat

#28 [Backend] 예정된/지난 여행 목록 API
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/dto/TravelListRes.java
  src/main/java/site/packit/packit/domain/travel/repository/TravelMemberRepository.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: feat

#30 [Backend] 여행 체크리스트 상세 조회 API
  src/main/java/site/packit/packit/domain/cluster/repository/ClusterRepository.java
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/dto/TravelCategory.java
  src/main/java/site/packit/packit/domain/travel/dto/TravelCluster.java
  src/main/java/site/packit/packit/domain/travel/dto/TravelDetailRes.java
  src/main/java/site/packit/packit/domain/travel/dto/TravelItem.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: feat

#32 [Backend] 할 일 그룹 (클러스터) 관련 API
  src/main/java/site/packit/packit/domain/category/entity/Category.java
  src/main/java/site/packit/packit/domain/cluster/controller/ClusterController.java
  src/main/java/site/packit/packit/domain/cluster/dto/ClusterOrderReq.java
  src/main/java/site/packit/packit/domain/cluster/dto/CreateClusterReq.java
  src/main/java/site/packit/packit/domain/cluster/entity/Cluster.java
  src/main/java/site/packit/packit/domain/cluster/execption/ClusterErrorCode.java
  src/main/java/site/packit/packit/domain/cluster/repository/ClusterRepository.java
  src/main/java/site/packit/packit/domain/cluster/service/ClusterService.java
  src/main/java/site/packit/packit/domain/item/entity/Item.java
  src/main/java/site/packit/packit/domain/travel/entity/Travel.java
Labels: feat, refactor

#34 [Backend] 카테고리 관련 API
  src/main/java/site/packit/packit/domain/category/controller/CategoryController.java
  src/main/java/site/packit/packit/domain/category/dto/CreateCategoryReq.java
  src/main/java/site/packit/packit/domain/category/dto/UpdateCategoryReq.java
  src/main/java/site/packit/packit/domain/category/entity/Category.java
  src/main/java/site/packit/packit/domain/category/repository/CategoryRepository.java
  src/main/java/site/packit/packit/domain/category/service/CategoryService.java
  src/main/java/site/packit/packit/domain/cluster/entity/Cluster.java
  src/main/java/site/packit/packit/domain/cluster/execption/ClusterErrorCode.java
  src/main/java/site/packit/packit/domain/item/entity/Item.java
Labels: feat

#36 [Backend] 아이템 관련 API
  src/main/java/site/packit/packit/domain/category/controller/CategoryController.java
  src/main/java/site/packit/packit/domain/item/controller/ItemController.java
  src/main/java/site/packit/packit/domain/item/dto/CreateItemReq.java
  src/main/java/site/packit/packit/domain/item/repository/ItemRepository.java
  src/main/java/site/packit/packit/domain/item/service/ItemService.java
Labels: feat

#38 [Backend] 여행 관련 마무리 작업
  src/main/java/site/packit/packit/domain/cluster/repository/ClusterRepository.java
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/dto/TravelCategory.java
  src/main/java/site/packit/packit/domain/travel/dto/TravelCluster.java
  src/main/java/site/packit/packit/domain/travel/repository/TravelMemberRepository.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: feat

#39 feat: 여행 조회 API 추가
  src/main/java/site/packit/packit/domain/travel/controller/TravelController.java
  src/main/java/site/packit/packit/domain/travel/service/TravelService.java
Labels: feat, refactor
